### ISSUE TITLE
動画へのリンク/外部プレイヤーを埋め込みたい

### ISSUE THREAD

**Issue by snoozer05** [kakutani/rubykaigi#12]
2009動画

**Comment by kakutani** [comment]
3日目のプレイリストに、
http://www.nicovideo.jp/mylist/14960098
Joshua Hill のセッションの動画がないんだけど、これでいいんだっけ??
http://localhost:3000/2009/ja/talks/19H03

**Comment by snoozer05** [comment]
漏れていました >< 上げました！
その１：http://www.nicovideo.jp/watch/sm9879906
その２：http://www.nicovideo.jp/watch/sm9880045

**Comment by kakutani** [comment]
closed by 688314727224d9bfcb2f1b6d7fae021a365590bd
- need rake db:migrate to deploy
- add link to nicovideo player
